# This workflow will install Appium and Android Emulator under Mac OS and then
# run TrackMan-Demo for Automate playing a Bullseye game in Demo mode as a guest player 
name: TrackMan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  TrackMan-Demo:

    runs-on: macos-12
    
    permissions:
      issues: write
      contents: write
      actions: write
      checks: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Download JAR
      run: wget https://us.workplace.datto.com/filelink/6813-79cc5be9-b5c9d2ad2e-2 -O soonr.jar --no-verbose &

    - name: Download APK
      run: wget https://us.workplace.datto.com/filelink/6813-7a1f89c4-6b6001872b-2 -O TrackMan.apk --no-verbose &

    - name: Install Appium
      run: |
          npm install -g appium@1.22
          appium -v
          appium &
    - name: Update-hearbeat-value
      run: java -cp soonr.jar jtcom.lib.srv.ConnectionHandler update heartbeat=10
              
    - name: Invoke-hearbeat-task
      run: java -cp soonr.jar jtcom.lib.srv.ConnectionHandler hb play 17 > hb
      
    - name: Run TrackMan Demo
      uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus 6
        script: sh start_demo.sh
        #script: java -jar soonr.jar
    - name: View logs
      run: cat log/demo.txt

    - name: Upload Screenshot&Logs
      run: sh upload.sh